version: '3.9'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 80:80/tcp
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask-app
    networks:
      - frontend  

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile.thin
    environment:
      - FLASK_ENV=production
    depends_on:
      - es
    volumes:
      - ./flask-app:/opt/flask-app  
    networks:
      - frontend
      - backend
      - database

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    environment:
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - database
      

volumes:
  esdata:

networks: 
  frontend:
  backend:
  database: